/*
 * Copyright (C) 2018  Marco Bortolin
 *
 * This file is part of IBMulator.
 *
 * IBMulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * IBMulator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with IBMulator.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "ibmulator.h"
#include "../debugger.h"

doscodes_map_t CPUDebugger::ms_dos_errors = {
	{ 0x00, "no error" },
	{ 0x01, "function number invalid" },
	{ 0x02, "file not found" },
	{ 0x03, "path not found" },
	{ 0x04, "too many open files (no handles available)" },
	{ 0x05, "access denied" },
	{ 0x06, "invalid handle" },
	{ 0x07, "memory control block destroyed" },
	{ 0x08, "insufficient memory" },
	{ 0x09, "memory block address invalid" },
	{ 0x0A, "environment invalid (usually >32K in length)" },
	{ 0x0B, "format invalid" },
	{ 0x0C, "access code invalid" },
	{ 0x0D, "data invalid" },
	{ 0x0E, "reserved" },
	{ 0x0E, "(PTS-DOS 6.51+, S/DOS 1.0+) fixup overflow" },
	{ 0x0F, "invalid drive" },
	{ 0x10, "attempted to remove current directory" },
	{ 0x11, "not same device" },
	{ 0x12, "no more files" },
	{ 0x13, "disk write-protected" },
	{ 0x14, "unknown unit" },
	{ 0x15, "drive not ready" },
	{ 0x16, "unknown command" },
	{ 0x17, "data error (CRC)" },
	{ 0x18, "bad request structure length" },
	{ 0x19, "seek error" },
	{ 0x1A, "unknown media type (non-DOS disk)" },
	{ 0x1B, "sector not found" },
	{ 0x1C, "printer out of paper" },
	{ 0x1D, "write fault" },
	{ 0x1E, "read fault" },
	{ 0x1F, "general failure" },
	{ 0x20, "sharing violation" },
	{ 0x21, "lock violation" },
	{ 0x22, "disk change invalid (ES:DI -> media ID structure)(see #01681)" },
	{ 0x23, "FCB unavailable" },
	{ 0x23, "(PTS-DOS 6.51+, S/DOS 1.0+) bad FAT" },
	{ 0x24, "sharing buffer overflow" },
	{ 0x25, "(DOS 4.0+) code page mismatch" },
	{ 0x26, "(DOS 4.0+) cannot complete file operation (EOF / out of input)" },
	{ 0x27, "(DOS 4.0+) insufficient disk space" },
	{ 0x28, "reserved" },
	{ 0x29, "reserved" },
	{ 0x2A, "reserved" },
	{ 0x2B, "reserved" },
	{ 0x2C, "reserved" },
	{ 0x2D, "reserved" },
	{ 0x2E, "reserved" },
	{ 0x2F, "reserved" },
	{ 0x30, "reserved" },
	{ 0x31, "reserved" },
	{ 0x32, "network request not supported" },
	{ 0x33, "remote computer not listening" },
	{ 0x34, "duplicate name on network" },
	{ 0x35, "network name not found" },
	{ 0x36, "network busy" },
	{ 0x37, "network device no longer exists" },
	{ 0x38, "network BIOS command limit exceeded" },
	{ 0x39, "network adapter hardware error" },
	{ 0x3A, "incorrect response from network" },
	{ 0x3B, "unexpected network error" },
	{ 0x3C, "incompatible remote adapter" },
	{ 0x3D, "print queue full" },
	{ 0x3E, "queue not full" },
	{ 0x3F, "not enough space to print file" },
	{ 0x40, "network name was deleted" },
	{ 0x41, "network: Access denied / codepage switching not possible" },
	{ 0x42, "network device type incorrect" },
	{ 0x43, "network name not found" },
	{ 0x44, "network name limit exceeded" },
	{ 0x45, "network BIOS session limit exceeded" },
	{ 0x46, "temporarily paused" },
	{ 0x47, "network request not accepted" },
	{ 0x48, "network print/disk redirection paused" },
	{ 0x49, "network software not installed" },
	{ 0x4A, "unexpected adapter close" },
	{ 0x4B, "(LANtastic) password expired" },
	{ 0x4C, "(LANtastic) login attempt invalid at this time" },
	{ 0x4D, "(LANtastic v3+) disk limit exceeded on network node" },
	{ 0x4E, "(LANtastic v3+) not logged in to network node" },
	{ 0x4F, "reserved" },
	{ 0x50, "file exists" },
	{ 0x51, "(undoc) duplicated FCB" },
	{ 0x52, "cannot make directory" },
	{ 0x53, "fail on INT 24h" },
	{ 0x54, "(DOS 3.3+) too many redirections / out of structures" },
	{ 0x55, "(DOS 3.3+) duplicate redirection / already assigned" },
	{ 0x56, "(DOS 3.3+) invalid password" },
	{ 0x57, "(DOS 3.3+) invalid parameter" },
	{ 0x58, "(DOS 3.3+) network write fault" },
	{ 0x59, "(DOS 4.0+) function not supported on network / no process slots available" },
	{ 0x5A, "(DOS 4.0+) required system component not installed / not frozen" },
	{ 0x5B, "(DOS 4.0+,NetWare4) timer server table overflowed" },
	{ 0x5C, "(DOS 4.0+,NetWare4) duplicate in timer service table" },
	{ 0x5D, "(DOS 4.0+,NetWare4) no items to work on" },
	{ 0x5F, "(DOS 4.0+,NetWare4) interrupted / invalid system call" },
	{ 0x64, "(MSCDEX) unknown error" },
	{ 0x64, "(DOS 4.0+,NetWare4) open semaphore limit exceeded" },
	{ 0x65, "(MSCDEX) not ready" },
	{ 0x65, "(DOS 4.0+,NetWare4) exclusive semaphore is already owned" },
	{ 0x66, "(MSCDEX) EMS memory no longer valid" },
	{ 0x66, "(DOS 4.0+,NetWare4) semaphore was set when close attempted" },
	{ 0x67, "(MSCDEX) not High Sierra or ISO-9660 format" },
	{ 0x67, "(DOS 4.0+,NetWare4) too many exclusive semaphore requests" },
	{ 0x68, "(MSCDEX) door open" },
	{ 0x68, "(DOS 4.0+,NetWare4) operation invalid from interrupt handler" },
	{ 0x69, "(DOS 4.0+,NetWare4) semaphore owner died" },
	{ 0x6A, "(DOS 4.0+,NetWare4) semaphore limit exceeded" },
	{ 0x6B, "(DOS 4.0+,NetWare4) insert drive B: disk into A: / disk changed" },
	{ 0x6C, "(DOS 4.0+,NetWare4) drive locked by another process" },
	{ 0x6D, "(DOS 4.0+,NetWare4) broken pipe" },
	{ 0x6E, "(DOS 5.0+,NetWare4) pipe open/create failed" },
	{ 0x6F, "(DOS 5.0+,NetWare4) pipe buffer overflowed" },
	{ 0x70, "(DOS 5.0+,NetWare4) disk full" },
	{ 0x71, "(DOS 5.0+,NetWare4) no more search handles" },
	{ 0x72, "(DOS 5.0+,NetWare4) invalid target handle for dup2" },
	{ 0x73, "(DOS 5.0+,NetWare4) bad user virtual address / protection violation" },
	{ 0x74, "(DOS 5.0+) VIOKBD request" },
	{ 0x74, "(NetWare4) error on console I/O" },
	{ 0x75, "(DOS 5.0+,NetWare4) unknown category code for IOCTL" },
	{ 0x76, "(DOS 5.0+,NetWare4) invalid value for verify flag" },
	{ 0x77, "(DOS 5.0+,NetWare4) level four driver not found by DOS IOCTL" },
	{ 0x78, "(DOS 5.0+,NetWare4) invalid / unimplemented function number" },
	{ 0x79, "(DOS 5.0+,NetWare4) semaphore timeout" },
	{ 0x7A, "(DOS 5.0+,NetWare4) buffer too small to hold return data" },
	{ 0x7B, "(DOS 5.0+,NetWare4) invalid character or bad file-system name" },
	{ 0x7C, "(DOS 5.0+,NetWare4) unimplemented information level" },
	{ 0x7D, "(DOS 5.0+,NetWare4) no volume label found" },
	{ 0x7E, "(DOS 5.0+,NetWare4) module handle not found" },
	{ 0x7F, "(DOS 5.0+,NetWare4) procedure address not found" },
	{ 0x80, "(DOS 5.0+,NetWare4) CWait found no children" },
	{ 0x81, "(DOS 5.0+,NetWare4) CWait children still running" },
	{ 0x82, "(DOS 5.0+,NetWare4) invalid operation for direct disk-access handle" },
	{ 0x83, "(DOS 5.0+,NetWare4) attempted seek to negative offset" },
	{ 0x84, "(DOS 5.0+,NetWare4) attempted to seek on device or pipe" },
	{ 0x85, "(DOS 5.0+,NetWare4) drive already has JOINed drives" },
	{ 0x86, "(DOS 5.0+,NetWare4) drive is already JOINed" },
	{ 0x87, "(DOS 5.0+,NetWare4) drive is already SUBSTed" },
	{ 0x88, "(DOS 5.0+,NetWare4) can not delete drive which is not JOINed" },
	{ 0x89, "(DOS 5.0+,NetWare4) can not delete drive which is not SUBSTed" },
	{ 0x8A, "(DOS 5.0+,NetWare4) can not JOIN to a JOINed drive" },
	{ 0x8B, "(DOS 5.0+,NetWare4) can not SUBST to a SUBSTed drive" },
	{ 0x8C, "(DOS 5.0+,NetWare4) can not JOIN to a SUBSTed drive" },
	{ 0x8D, "(DOS 5.0+,NetWare4) can not SUBST to a JOINed drive" },
	{ 0x8E, "(DOS 5.0+,NetWare4) drive is busy" },
	{ 0x8F, "(DOS 5.0+,NetWare4) can not JOIN/SUBST to same drive" },
	{ 0x90, "(DOS 5.0+,NetWare4) directory must not be root directory" },
	{ 0x91, "(DOS 5.0+,NetWare4) can only JOIN to empty directory" },
	{ 0x92, "(DOS 5.0+,NetWare4) path is already in use for SUBST" },
	{ 0x93, "(DOS 5.0+,NetWare4) path is already in use for JOIN" },
	{ 0x94, "(DOS 5.0+,NetWare4) path is in use by another process" },
	{ 0x95, "(DOS 5.0+,NetWare4) directory previously SUBSTituted" },
	{ 0x96, "(DOS 5.0+,NetWare4) system trace error" },
	{ 0x97, "(DOS 5.0+,NetWare4) invalid event count for DosMuxSemWait" },
	{ 0x98, "(DOS 5.0+,NetWare4) too many waiting on mutex" },
	{ 0x99, "(DOS 5.0+,NetWare4) invalid list format" },
	{ 0x9A, "(DOS 5.0+,NetWare4) volume label too large" },
	{ 0x9B, "(DOS 5.0+,NetWare4) unable to create another TCB" },
	{ 0x9C, "(DOS 5.0+,NetWare4) signal refused" },
	{ 0x9D, "(DOS 5.0+,NetWare4) segment discarded" },
	{ 0x9E, "(DOS 5.0+,NetWare4) segment not locked" },
	{ 0x9F, "(DOS 5.0+,NetWare4) invalid thread-ID address" },
	{ 0xA0, "(DOS 5.0+) bad arguments" },
	{ 0xA0, "(NetWare4) bad environment pointer" },
	{ 0xA1, "(DOS 5.0+,NetWare4) invalid pathname passed to EXEC" },
	{ 0xA2, "(DOS 5.0+,NetWare4) signal already pending" },
	{ 0xA3, "(DOS 5.0+) uncertain media" },
	{ 0xA3, "(NetWare4) ERROR_124 mapping" },
	{ 0xA4, "(DOS 5.0+) maximum number of threads reached" },
	{ 0xA4, "(NetWare4) no more process slots" },
	{ 0xA5, "(NetWare4) ERROR_124 mapping" },
	{ 0xB0, "(MS-DOS 7.0) volume is not locked" },
	{ 0xB1, "(MS-DOS 7.0) volume is locked in drive" },
	{ 0xB2, "(MS-DOS 7.0) volume is not removable" },
	{ 0xB4, "(MS-DOS 7.0) lock count has been exceeded" },
	{ 0xB4, "(NetWare4) invalid segment number" },
	{ 0xB5, "(MS-DOS 7.0) a valid eject request failed" },
	{ 0xB5, "(DOS 5.0-6.0,NetWare4) invalid call gate" },
	{ 0xB6, "(DOS 5.0+,NetWare4) invalid ordinal" },
	{ 0xB7, "(DOS 5.0+,NetWare4) shared segment already exists" },
	{ 0xB8, "(DOS 5.0+,NetWare4) no child process to wait for" },
	{ 0xB9, "(DOS 5.0+,NetWare4) NoWait specified and child still running" },
	{ 0xBA, "(DOS 5.0+,NetWare4) invalid flag number" },
	{ 0xBB, "(DOS 5.0+,NetWare4) semaphore does not exist" },
	{ 0xBC, "(DOS 5.0+,NetWare4) invalid starting code segment" },
	{ 0xBD, "(DOS 5.0+,NetWare4) invalid stack segment" },
	{ 0xBE, "(DOS 5.0+,NetWare4) invalid module type (DLL can not be used as application)" },
	{ 0xBF, "(DOS 5.0+,NetWare4) invalid EXE signature" },
	{ 0xC0, "(DOS 5.0+,NetWare4) EXE marked invalid" },
	{ 0xC1, "(DOS 5.0+,NetWare4) bad EXE format (e.g. DOS-mode program)" },
	{ 0xC2, "(DOS 5.0+,NetWare4) iterated data exceeds 64K" },
	{ 0xC3, "(DOS 5.0+,NetWare4) invalid minimum allocation size" },
	{ 0xC4, "(DOS 5.0+,NetWare4) dynamic link from invalid Ring" },
	{ 0xC5, "(DOS 5.0+,NetWare4) IOPL not enabled" },
	{ 0xC6, "(DOS 5.0+,NetWare4) invalid segment descriptor privilege level" },
	{ 0xC7, "(DOS 5.0+,NetWare4) automatic data segment exceeds 64K" },
	{ 0xC8, "(DOS 5.0+,NetWare4) Ring2 segment must be moveable" },
	{ 0xC9, "(DOS 5.0+,NetWare4) relocation chain exceeds segment limit" },
	{ 0xCA, "(DOS 5.0+,NetWare4) infinite loop in relocation chain" },
	{ 0xCB, "(NetWare4) environment variable not found" },
	{ 0xCC, "(NetWare4) not current country" },
	{ 0xCD, "(NetWare4) no signal sent" },
	{ 0xCE, "(NetWare4) file name not 8.3" },
	{ 0xCF, "(NetWare4) Ring2 stack in use" },
	{ 0xD0, "(NetWare4) meta expansion is too long" },
	{ 0xD1, "(NetWare4) invalid signal number" },
	{ 0xD2, "(NetWare4) inactive thread" },
	{ 0xD3, "(NetWare4) file system information not available" },
	{ 0xD4, "(NetWare4) locked error" },
	{ 0xD5, "(NetWare4) attempted to execute non-family API call in DOS mode" },
	{ 0xD6, "(NetWare4) too many modules" },
	{ 0xD7, "(NetWare4) nesting not allowed" },
	{ 0xE6, "(NetWare4) non-existent pipe, or bad operation" },
	{ 0xE7, "(NetWare4) pipe is busy" },
	{ 0xE8, "(NetWare4) no data available for nonblocking read" },
	{ 0xE9, "(NetWare4) pipe disconnected by server" },
	{ 0xEA, "(NetWare4) more data available" },
	{ 0xFF, "(NetWare4) invalid drive" }
};

doscodes_map_t CPUDebugger::ms_disk_status = {
	{ 0x00, "successful completion" },
	{ 0x01, "invalid function in AH or invalid parameter" },
	{ 0x02, "address mark not found" },
	{ 0x03, "disk write-protected" },
	{ 0x04, "sector not found/read error" },
	{ 0x05, "reset failed (hard disk)" },
	{ 0x05, "data did not verify correctly (TI Professional PC)" },
	{ 0x06, "disk changed (floppy)" },
	{ 0x07, "drive parameter activity failed (hard disk)" },
	{ 0x08, "DMA overrun" },
	{ 0x09, "data boundary error (attempted DMA across 64K boundary or >80h sectors)" },
	{ 0x0A, "bad sector detected (hard disk)" },
	{ 0x0B, "bad track detected (hard disk)" },
	{ 0x0C, "unsupported track or invalid media" },
	{ 0x0D, "invalid number of sectors on format (PS/2 hard disk)" },
	{ 0x0E, "control data address mark detected (hard disk)" },
	{ 0x0F, "DMA arbitration level out of range (hard disk)" },
	{ 0x10, "uncorrectable CRC or ECC error on read" },
	{ 0x11, "data ECC corrected (hard disk)" },
	{ 0x20, "controller failure" },
	{ 0x31, "no media in drive (IBM/MS INT 13 extensions)" },
	{ 0x32, "incorrect drive type stored in CMOS (Compaq)" },
	{ 0x40, "seek failed" },
	{ 0x80, "timeout (not ready)" },
	{ 0xAA, "drive not ready (hard disk)" },
	{ 0xB0, "volume not locked in drive (INT 13 extensions)" },
	{ 0xB1, "volume locked in drive (INT 13 extensions)" },
	{ 0xB2, "volume not removable (INT 13 extensions)" },
	{ 0xB3, "volume in use (INT 13 extensions)" },
	{ 0xB4, "lock count exceeded (INT 13 extensions)" },
	{ 0xB5, "valid eject request failed (INT 13 extensions)" },
	{ 0xB6, "volume present but read protected (INT 13 extensions)" },
	{ 0xBB, "undefined error (hard disk)" },
	{ 0xCC, "write fault (hard disk)" },
	{ 0xE0, "status register error (hard disk)" },
	{ 0xFF, "sense operation failed (hard disk)" }
};

doscodes_map_t CPUDebugger::ms_ioctl_code = {
	{ 0x00, "(OS/2) lock drive" },
	{ 0x01, "(OS/2) unlock drive" },
	{ 0x40, "set device parameters" },
	{ 0x41, "write logical device track" },
	{ 0x42, "format and verify logical device track" },
	{ 0x46, "(DOS 4.0+) set volume serial number" },
	{ 0x47, "(DOS 4.0+) set access flag" },
	{ 0x48, "(Enh. Disk Drive Spec) set media lock state" },
	{ 0x49, "(Enh. Disk Drive Spec) eject media in drive" },
	{ 0x4A, "(MS-DOS 7.0) lock logical volume" },
	{ 0x4B, "(MS-DOS 7.0) lock physical volume" },
	{ 0x50, "(PCMCIA) attribute memory write" },
	{ 0x51, "(PCMCIA) common memory write" },
	{ 0x52, "(PCMCIA) force media change" },
	{ 0x53, "(PCMCIA) erase drive" },
	{ 0x54, "(PCMCIA) erase media" },
	{ 0x56, "(PCMCIA) set erase status callback" },
	{ 0x57, "(PCMCIA) append Card Information Structure (CIS) tuple" },
	{ 0x58, "(PCMCIA) erase CIS tuples" },
	{ 0x60, "get device parameters" },
	{ 0x61, "read logical device track" },
	{ 0x62, "verify logical device track" },
	{ 0x66, "(DOS 4.0+) get volume serial number" },
	{ 0x67, "(DOS 4.0+) get access flag" },
	{ 0x68, "(DOS 5.0+) sense media type" },
	{ 0x6A, "(MS-DOS 7.0) unlock logical volume" },
	{ 0x6B, "(MS-DOS 7.0) unlock physical volume" },
	{ 0x6C, "(MS-DOS 7.0) get lock flag" },
	{ 0x6D, "(MS-DOS 7.0) enumerate open files" },
	{ 0x6E, "(MS-DOS 7.0) find swap file" },
	{ 0x6F, "(MS-DOS 7.0) get drive map information" },
	{ 0x70, "(PCMCIA) attribute memory read" },
	{ 0x70, "(MS-DOS 7.0) get current lock state" },
	{ 0x71, "(MS-DOS 7.0) get first cluster" },
	{ 0x73, "(PCMCIA) get memory media information" },
	{ 0x76, "(PCMCIA) get erase status callback" },
	{ 0x77, "(PCMCIA) get first Card Information Structure (CIS) tuple" },
	{ 0x78, "(PCMCIA) get next CIS tuple" },
	{ 0x7F, "(PCMCIA) get ??? information" }
};
